//! Single source of truth for Vuho's model layout: names, pinned upstream
//! revisions, component lists, and the env-var → bundle → workspace-dev →
//! user-data resolution chain shared by `vuho-stt-engine` and (once built)
//! `vuho-model-fetch` (CONSTITUTION rule 26 — one chokepoint, not two
//! near-identical copies).
//!
//! `models.manifest.json` (repo root) is the ONE place model names,
//! revisions, component lists, and the bundle ID are written down; this
//! crate embeds it at compile time via `include_str!`. The
//! provisioning/packaging scripts under `scripts/` read the very same file
//! at runtime via `scripts/manifest-lib.sh`, so a manifest edit can
//! never desync Rust from the scripts — renaming a component in the
//! manifest breaks both sides loudly instead of silently drifting.
//!
//! `models.lock.json` (repo root, generated by `scripts/lock-model.sh`) is
//! embedded the same way and exposed via [`lock`] (ADR-020): it carries
//! per-file sizes and SHA-256 hashes so a downloader can verify a fetched
//! model tree against the exact bytes pinned at `models.manifest.json`'s
//! revision. Verification is scoped to models this crate's own resolver
//! places under [`user_models_dir`] — see [`resolve_model_folder`]'s doc
//! comment and ADR-020's "central invariant".
//!
//! `atomic_write` is the one temp-file + `sync_all` + `rename` +
//! parent-dir-fsync sequence used by every caller that persists a file
//! durably (`vuho-settings`'s `SettingsStore`, and the model downloader's
//! sidecar manifest) — CONSTITUTION rule 26.
//!
//! Std-only: no macOS-specific dependencies, so this crate builds on any
//! host — only its callers are macOS-only.

use std::collections::BTreeMap;
use std::ffi::OsStr;
use std::fmt::Write as _;
use std::io::Write as _;
use std::path::{Component, Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::OnceLock;

/// The embedded manifest source — see `models.manifest.json` at the
/// workspace root.
const MANIFEST_JSON: &str = include_str!("../../../models.manifest.json");

/// The embedded lock source — see `models.lock.json` at the workspace root
/// (generated by `scripts/lock-model.sh`).
const LOCK_JSON: &str = include_str!("../../../models.lock.json");

/// Parsed `models.manifest.json`.
#[derive(Debug, serde::Deserialize)]
pub struct Manifest {
    /// macOS bundle identifier (`CFBundleIdentifier`), e.g. `tech.iurii.vuho`.
    pub bundle_id: String,
    /// Every selectable STT model, keyed by model id.
    pub stt: SttManifest,
    /// Silero VAD provisioning metadata (fetched for a future direct-`ort`
    /// swap; the app's actual VAD path uses `voice_activity_detector`'s
    /// embedded weights, not these files — see `vuho-stt-engine`'s `vad`
    /// module doc comment).
    pub silero: SileroManifest,
}

/// Every selectable STT model, plus the env vars that override where the
/// selected one is resolved from.
#[derive(Debug, serde::Deserialize)]
pub struct SttManifest {
    /// Id of the model used when the user has expressed no preference.
    pub default_model: String,
    /// Env var that overrides the full resolved folder path.
    pub env_folder: String,
    /// Env var that overrides just `dir_name`.
    pub env_name: String,
    /// Every known STT model, keyed by model id.
    pub models: BTreeMap<String, SttModel>,
}

/// One STT model's manifest entry.
#[derive(Debug, serde::Deserialize)]
pub struct SttModel {
    /// Human-readable name for the Settings UI.
    pub display_name: String,
    /// Which engine implementation decodes this model.
    pub backend: Backend,
    /// Upstream Hugging Face repo.
    pub repo: String,
    /// Pinned commit revision.
    pub revision: String,
    /// Directory name under `models/` (dev) or `Contents/Resources/`
    /// (bundled) — the default, overridable via [`SttManifest::env_name`].
    pub dir_name: String,
    /// Lowest macOS version that can run this model, `"MAJOR.MINOR"`.
    pub min_macos: String,
    /// Every required asset, keyed by the role the backend loads it as
    /// (`preprocessor`, `encoder`, …) — named roles rather than a
    /// positional list, so a backend asks for the file it needs by name
    /// instead of by index (ADR-019).
    pub assets: BTreeMap<String, String>,
}

/// Which engine implementation decodes a model.
#[derive(Clone, Copy, Debug, PartialEq, Eq, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Backend {
    /// Parakeet-TDT: RNN-T greedy decode over a sliding 15 s window.
    ParakeetTdt,
    /// Canary: attention encoder-decoder over a fixed 15 s window.
    CanaryAed,
}

impl SttManifest {
    /// The model registered under `id`.
    #[must_use]
    pub fn model(&self, id: &str) -> Option<&SttModel> {
        self.models.get(id)
    }

    /// The model [`Self::default_model`] names.
    ///
    /// # Panics
    ///
    /// Panics if `default_model` names no registered model — an invariant
    /// of the embedded manifest, pinned by
    /// `default_model_names_a_registered_model`.
    #[must_use]
    pub fn default_model_entry(&self) -> &SttModel {
        self.model(&self.default_model)
            .expect("manifest default_model must name a registered model")
    }

    /// The [`ModelSpec`] for `id`, for [`resolve_model_folder`].
    ///
    /// **The two env-var overrides are manifest-wide, not per model**:
    /// [`Self::env_folder`] and [`Self::env_name`] live on the manifest, so
    /// every id gets the same pair and a set `VUHO_MODEL_FOLDER` points
    /// *every* model at that one directory. `availability_all` then reports
    /// each of them `Ready`/`EnvOverride`, the Settings list offers them
    /// all, and selecting one whose backend does not match the files in
    /// that directory fails at load time.
    ///
    /// This is deliberate, not an oversight. The override exists for
    /// `test-stt-ffi --model <id>`, `cargo test`, and packaging scripts,
    /// which point it at whichever single model tree they are exercising
    /// and select that model in the same breath. Scoping it to
    /// [`Self::default_model`] would leave no way to override a non-default
    /// model's folder at all, which is exactly what those callers do.
    #[must_use]
    pub fn spec_for(&self, id: &str) -> Option<ModelSpec<'_>> {
        self.model(id).map(|model| ModelSpec {
            env_folder: &self.env_folder,
            env_name: &self.env_name,
            default_dir_name: &model.dir_name,
        })
    }
}

impl SttModel {
    /// The filename this model ships for `role`, e.g. `"encoder"`.
    #[must_use]
    pub fn asset(&self, role: &str) -> Option<&str> {
        self.assets.get(role).map(String::as_str)
    }

    /// Every asset filename, sorted — the single source for existence
    /// checks and download allow-patterns.
    #[must_use]
    pub fn components(&self) -> Vec<&str> {
        let mut components: Vec<&str> = self.assets.values().map(String::as_str).collect();
        components.sort_unstable();
        components
    }
}

/// Silero VAD's manifest entry (provisioning metadata for `fetch-model.sh`
/// only).
#[derive(Debug, serde::Deserialize)]
pub struct SileroManifest {
    /// Upstream Hugging Face repo.
    pub repo: String,
    /// Pinned commit revision.
    pub revision: String,
    /// Directory name under `models/`.
    pub dir_name: String,
    /// Files to fetch, relative to the repo root.
    pub components: Vec<String>,
}

/// Parse and return the embedded manifest, once.
///
/// # Panics
///
/// Panics if `models.manifest.json` fails to parse — an invalid manifest is
/// a build-time/first-use bug, not a recoverable runtime condition (every
/// caller needs a valid manifest to do anything at all, so there is no
/// meaningful fallback).
#[must_use]
pub fn manifest() -> &'static Manifest {
    // The `OnceLock` stores a `Result` so `get_or_init` can never panic
    // (CONSTITUTION rule 17 — a panic inside `get_or_init` poisons it
    // permanently); the panic on a malformed manifest happens out here.
    static MANIFEST: OnceLock<Result<Manifest, serde_json::Error>> = OnceLock::new();
    MANIFEST
        .get_or_init(|| serde_json::from_str(MANIFEST_JSON))
        .as_ref()
        .expect("embedded models.manifest.json must parse")
}

/// Parsed `models.lock.json`: per-file integrity data for the models the
/// manifest names, pinned at the manifest's revision (ADR-020).
#[derive(Debug, serde::Deserialize)]
pub struct Lock {
    /// Lock schema version — bumped whenever the shape below changes.
    pub schema_version: u32,
    /// Each model's locked file set, keyed by the same model id the
    /// manifest uses.
    pub models: BTreeMap<String, SttLock>,
}

impl Lock {
    /// The locked file set for `id`.
    #[must_use]
    pub fn model(&self, id: &str) -> Option<&SttLock> {
        self.models.get(id)
    }
}

/// One model's locked file set: what a complete, untampered download must
/// contain.
#[derive(Debug, serde::Deserialize)]
pub struct SttLock {
    /// Directory name under `user_models_dir()` this lock describes —
    /// mirrors (and must match) `SttModel::dir_name`.
    pub dir_name: String,
    /// Pinned commit revision this lock was generated against — mirrors
    /// (and must match) `SttModel::revision`.
    pub revision: String,
    /// Sum of every locked file's `size`, for progress totals and the
    /// `ModelStatus::Missing { total_bytes }` a resolver miss reports.
    pub total_bytes: u64,
    /// Every locked file, path relative to the model directory.
    pub files: Vec<LockedFile>,
}

/// One locked file: its path (relative to the model directory), exact
/// size, and SHA-256 hash of its content.
#[derive(Debug, serde::Deserialize)]
pub struct LockedFile {
    /// Path relative to the model directory, e.g.
    /// `"ParakeetDecoder.mlmodelc/model.mil"`.
    pub path: String,
    /// Exact expected file size in bytes.
    pub size: u64,
    /// Hex-encoded SHA-256 of the file's content.
    pub sha256: String,
}

/// Parse and return the embedded lock, once.
///
/// Mirrors [`manifest`]'s `OnceLock<Result<...>>` pattern exactly
/// (CONSTITUTION rule 17): the `Result` itself is cached, not just the
/// `Ok` value, so a malformed `models.lock.json` cannot poison the lock
/// into a permanently-unusable state — every call re-observes the same
/// parse failure instead of a generic "already panicked" state.
///
/// # Panics
///
/// Panics if `models.lock.json` fails to parse — an invalid lock is a
/// build-time/first-use bug (it is generated and committed by
/// `scripts/lock-model.sh`, never hand-edited), not a recoverable runtime
/// condition.
#[must_use]
pub fn lock() -> &'static Lock {
    static LOCK: OnceLock<Result<Lock, serde_json::Error>> = OnceLock::new();
    LOCK.get_or_init(|| serde_json::from_str(LOCK_JSON))
        .as_ref()
        .expect("embedded models.lock.json must parse")
}

/// The env-var names and default directory name for one model, extracted
/// from the manifest — the input to [`resolve_model_folder`].
pub struct ModelSpec<'a> {
    /// Env var that overrides the full resolved folder path.
    pub env_folder: &'a str,
    /// Env var that overrides just the directory name.
    pub env_name: &'a str,
    /// Default directory name (under `models/` or `Contents/Resources/`).
    pub default_dir_name: &'a str,
}

/// Why [`resolve_model`] could not name an existing model directory.
#[derive(Debug, Clone)]
pub enum ModelPathError {
    /// The directory name itself is unusable — see [`InvalidDirName`]. No
    /// candidate was built, so nothing was tried.
    InvalidDirName(InvalidDirName),
    /// No candidate location held an existing directory. Carries every
    /// candidate path the resolver actually tried, in the order it tried
    /// them (most to least authoritative — see [`resolve_model_folder`]'s
    /// doc comment), so callers can build an actionable, typed error naming
    /// all of them, not just the last.
    NotFound {
        /// Every candidate path tried, in order.
        tried: Vec<PathBuf>,
    },
}

impl std::fmt::Display for ModelPathError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidDirName(invalid) => invalid.fmt(f),
            Self::NotFound { tried } => {
                let tried = tried
                    .iter()
                    .map(|p| p.display().to_string())
                    .collect::<Vec<_>>()
                    .join(", ");
                write!(f, "model folder not found — tried: {tried}")
            }
        }
    }
}

impl std::error::Error for ModelPathError {}

impl From<InvalidDirName> for ModelPathError {
    fn from(invalid: InvalidDirName) -> Self {
        Self::InvalidDirName(invalid)
    }
}

/// A model directory name that is not a plain directory name.
///
/// The name is validated where it is produced ([`dir_name_for`]) rather
/// than at the two places it is dangerous, because it is dangerous at both:
/// `vuho-model-fetch` joins it onto [`user_models_dir`] to *download* into,
/// and joins it again to recursively *delete*. `Path::starts_with` compares
/// whole components, so `..` is simply another component and
/// `<user_dir>/../../../../tmp/victim` starts with `<user_dir>` by that
/// test while the OS resolves the `..` at open time onto an unrelated
/// directory. One `Component::Normal` and nothing else is the property that
/// makes the join mean what the guard reads it as.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InvalidDirName {
    /// Where the rejected value came from: the env var that set it, or
    /// [`MANIFEST_ORIGIN`] when the manifest's own `dir_name` is at fault.
    pub origin: String,
    /// The rejected value, verbatim.
    pub value: String,
}

impl std::fmt::Display for InvalidDirName {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "model directory name {:?} (from {}) is not a single plain directory name — no separators, no `.` or `..`, no drive or root",
            self.value, self.origin
        )
    }
}

impl std::error::Error for InvalidDirName {}

/// [`InvalidDirName::origin`] for a name that came from the embedded
/// manifest rather than from an env var.
pub const MANIFEST_ORIGIN: &str = "models.manifest.json";

/// `name` if it is exactly one [`Component::Normal`] and nothing else.
fn plain_dir_name(name: String, origin: &str) -> Result<String, InvalidDirName> {
    let mut components = Path::new(&name).components();
    match (components.next(), components.next()) {
        (Some(Component::Normal(only)), None) if only == OsStr::new(&name) => Ok(name),
        _ => Err(InvalidDirName {
            origin: origin.to_owned(),
            value: name,
        }),
    }
}

fn non_empty_env(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|s| !s.is_empty())
}

/// `Contents/Resources` of the innermost `.app` bundle enclosing `exe`, or
/// `None` if no ancestor directory is actually an app bundle.
///
/// Walks `exe`'s ancestors from most to least specific (`Path::ancestors`)
/// rather than string-searching for the literal substring `".app/Contents"`
/// in the path — the string search had two failure modes this walk fixes:
/// a *nested* bundle (e.g. a plug-in's `.app` inside a host app's
/// `Contents/PlugIns/`) would match the outermost `.app` first (the
/// leftmost occurrence), not the one actually enclosing `exe`; and a
/// coincidentally-named sibling directory like `Contents-backup` shares
/// `".app/Contents"` as a literal prefix of its own name, so the string
/// search would silently match it too. This walk instead requires the
/// ancestor itself to have the `.app` extension AND to contain a real
/// `Contents` directory (checked by name, not by prefix) before accepting
/// it.
fn resources_dir_for_exe(exe: &Path) -> Option<PathBuf> {
    exe.ancestors()
        .find(|dir| {
            dir.extension().is_some_and(|ext| ext == "app") && dir.join("Contents").is_dir()
        })
        .map(|app_dir| app_dir.join("Contents").join("Resources"))
}

/// `Contents/Resources` of the enclosing `.app`, if the running executable
/// is inside one. A bare `cargo run` binary (`target/debug/vuho`) has no
/// `.app` ancestor, so this is `None` there.
fn bundle_resources_dir() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    resources_dir_for_exe(&exe)
}

/// Workspace-relative `models/` directory, used by `cargo run` and `cargo
/// test`.
///
/// `CARGO_MANIFEST_DIR` is baked in at compile time
/// (`…/crates/vuho-model-paths`), so this is absolute and independent of the
/// current working directory. Any crate directly under `crates/` resolves
/// to the same workspace root this way, so centralizing the computation
/// here — rather than duplicating it per caller crate — is correct, not
/// incidental.
fn dev_models_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent() // crates/
        .and_then(Path::parent) // workspace root
        .expect("CARGO_MANIFEST_DIR should be two levels below the workspace root")
        .join("models")
}

/// The single definition of where Vuho downloads the model to (ADR-020):
/// `$HOME/Library/Application Support/Vuho/models`. The resolver's
/// lowest-priority candidate, and the one directory a downloader
/// (`vuho-model-fetch`) is ever allowed to write into.
///
/// `$HOME` is read directly via `std::env::var`, not the `dirs` crate:
/// this crate is deliberately std-only (ADR-019), and its only callers are
/// macOS-only, so hardcoding the macOS `Library/Application Support` layout
/// here is the correct scope, not a shortcut that happens to work.
///
/// Returns `None` — never a fabricated relative path, never a panic —
/// when `$HOME` is unset or empty. A caller that gets `None` here simply
/// doesn't have this candidate to try; [`resolve_model_folder`] treats it
/// exactly like a bundle candidate absent because the process isn't inside
/// an `.app`.
#[must_use]
pub fn user_models_dir() -> Option<PathBuf> {
    non_empty_env("HOME").map(|home| {
        Path::new(&home)
            .join("Library")
            .join("Application Support")
            .join("Vuho")
            .join("models")
    })
}

/// The directory name to resolve for `spec`: `spec.env_name`'s override, or
/// `spec.default_dir_name`.
///
/// Public so every caller that needs to name the model directory —
/// [`resolve_model_folder`]'s own candidate-building below, and
/// `vuho-model-fetch`'s downloader/availability check — agrees on the same
/// override, instead of `vuho-model-fetch` reading `Lock::stt.dir_name`
/// directly and silently ignoring an operator's `VUHO_MODEL_NAME` override
/// that `resolve_model_folder` already honors.
///
/// `spec.env_name` is manifest-wide: one value renames the directory of
/// **every** model, not just the selected one. See [`SttManifest::spec_for`]
/// for why that is deliberate.
///
/// # Errors
///
/// Returns [`InvalidDirName`] when the name is anything but a single plain
/// directory name — which is a hard refusal, never a fall back to the
/// manifest default, because a caller that quietly got the default would
/// then download into (or delete) a directory the operator did not ask for.
pub fn dir_name_for(spec: &ModelSpec<'_>) -> Result<String, InvalidDirName> {
    match non_empty_env(spec.env_name) {
        Some(override_name) => plain_dir_name(override_name, spec.env_name),
        None => plain_dir_name(spec.default_dir_name.to_owned(), MANIFEST_ORIGIN),
    }
}

/// Every candidate model-directory location for `spec`, most to least
/// authoritative — see [`resolve_model_folder`]'s doc comment for the
/// order and rationale. A candidate is included only when its source is
/// actually available (e.g. no bundle entry when not running inside an
/// `.app`, no user-dir entry when `$HOME` is unset) — the returned list is
/// exactly what gets tried, and exactly what [`ModelPathError::tried`]
/// reports on failure.
fn candidate_paths(spec: &ModelSpec<'_>) -> Result<Vec<Resolved>, InvalidDirName> {
    let dir_name = dir_name_for(spec)?;

    // The full-path override is terminal, not merely first: if the operator
    // named a folder, that folder is the answer or there is no answer.
    // Falling through to the bundle/dev/user candidates would mean a typo in
    // `VUHO_MODEL_FOLDER` silently loads a *different* model than the one
    // asked for, and reports success — the operator has no way to tell their
    // override was ignored. An error naming the path they actually typed is
    // the only honest outcome. (This is the pre-ADR-020 behavior, preserved
    // deliberately: the old `map_or_else` took its else-branch only when the
    // variable was unset.)
    if let Some(folder) = non_empty_env(spec.env_folder) {
        return Ok(vec![Resolved {
            path: PathBuf::from(folder),
            source: ModelSource::EnvOverride,
        }]);
    }

    let mut candidates = Vec::with_capacity(3);
    if let Some(resources) = bundle_resources_dir() {
        candidates.push(Resolved {
            path: resources.join(&dir_name),
            source: ModelSource::Bundle,
        });
    }
    candidates.push(Resolved {
        path: dev_models_dir().join(&dir_name),
        source: ModelSource::DevTree,
    });
    if let Some(user_dir) = user_models_dir() {
        candidates.push(Resolved {
            path: user_dir.join(&dir_name),
            source: ModelSource::UserData,
        });
    }

    Ok(candidates)
}

/// Which of [`resolve_model`]'s candidate locations a model directory came
/// from. Load-bearing beyond diagnostics: ADR-020 lets Vuho verify — and
/// delete — only the tree it downloaded itself, i.e. only
/// [`ModelSource::UserData`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ModelSource {
    /// The `env_folder` full-path override.
    EnvOverride,
    /// The enclosing `.app`'s `Contents/Resources/<name>`.
    Bundle,
    /// The workspace-relative `models/<name>` dev directory.
    DevTree,
    /// `<name>` under [`user_models_dir`] — the one tree a downloader
    /// writes into.
    UserData,
}

/// A resolved model directory and the candidate location it came from.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Resolved {
    /// The existing directory holding the model.
    pub path: PathBuf,
    /// Which candidate produced [`Self::path`].
    pub source: ModelSource,
}

/// Resolve a model directory — the single chokepoint any caller learns
/// where a model lives, shared by `vuho-stt-engine::resolve_model_folder`
/// and (via `availability()`) `vuho-model-fetch`.
///
/// Tries, in order, the first candidate that is an existing directory:
///
/// 1. `spec.env_folder` (full path override, e.g. `VUHO_MODEL_FOLDER`).
/// 2. The enclosing `.app`'s `Contents/Resources/<name>` — keeps a DMG
///    build offline from first launch.
/// 3. The workspace-relative `models/<name>` dev directory — `cargo run` /
///    `cargo test`; never exists for an end user.
/// 4. `<name>` under [`user_models_dir`] (ADR-020) — the one tree a
///    downloader ever writes into.
///
/// `<name>` is `spec.env_name`'s override, or `spec.default_dir_name`, and
/// must be a single plain directory name either way ([`dir_name_for`]).
///
/// Both env vars are manifest-wide, so candidate 1 in particular answers
/// for **every** model id, not only the one it was set for — see
/// [`SttManifest::spec_for`].
///
/// The order is deliberate, not incidental: candidate 3 before candidate 4
/// preserves `cargo run` / `cargo test` / `test-stt-ffi` behavior exactly
/// as it was before ADR-020 added the user-data candidate — a developer's
/// workspace `models/` checkout always wins over a stale download sitting
/// in `~/Library/Application Support/Vuho/models`.
///
/// Vuho's own resolver never downloads a model — a directory that isn't on
/// disk at any candidate is an error here rather than a silent network
/// fetch; only `vuho-model-fetch`, gated behind an explicit user action,
/// ever performs network I/O (ADR-020).
///
/// # Errors
///
/// Returns [`ModelPathError::InvalidDirName`] for an unusable directory
/// name, or [`ModelPathError::NotFound`] naming every candidate tried if
/// none of them is an existing directory.
pub fn resolve_model_folder(spec: &ModelSpec<'_>) -> Result<PathBuf, ModelPathError> {
    resolve_model(spec).map(|resolved| resolved.path)
}

/// [`resolve_model_folder`], plus which candidate location answered — the
/// distinction ADR-020's "Vuho owns only bytes it fetched" invariant is
/// built on.
///
/// # Errors
///
/// Returns [`ModelPathError::InvalidDirName`] when the directory name (or
/// its `env_name` override) is not a single plain directory name, and
/// [`ModelPathError::NotFound`] naming every candidate tried if none of
/// them is an existing directory.
pub fn resolve_model(spec: &ModelSpec<'_>) -> Result<Resolved, ModelPathError> {
    let candidates = candidate_paths(spec)?;
    match candidates.iter().find(|candidate| candidate.path.is_dir()) {
        Some(found) => Ok(found.clone()),
        None => Err(ModelPathError::NotFound {
            tried: candidates.into_iter().map(|c| c.path).collect(),
        }),
    }
}

/// Process-local counter for [`unique_temp_path`], so two racing callers in
/// the same process never pick the same temp-file name before either
/// `rename` lands.
static TEMP_SEQ: AtomicU64 = AtomicU64::new(0);

/// Build a unique temp-file path alongside `path`, in the same directory
/// (so [`atomic_write`]'s `rename` is a same-filesystem atomic move).
///
/// Uniqueness comes from the process ID plus a process-local monotonic
/// counter — not a timestamp, which two calls within the same clock tick
/// (the common case for a tight retry loop or two racing threads) could
/// collide on.
fn unique_temp_path(path: &Path) -> PathBuf {
    let seq = TEMP_SEQ.fetch_add(1, Ordering::Relaxed);
    let mut name = path
        .file_name()
        .map_or_else(|| "vuho".to_string(), |n| n.to_string_lossy().into_owned());
    let _ = write!(name, ".tmp.{}.{seq}", std::process::id());
    path.with_file_name(name)
}

/// Atomically replace the file at `path` with `bytes`.
///
/// Durability chain: write `bytes` to a unique temp file in `path`'s
/// parent directory → `File::sync_all` the temp file (flush its content to
/// durable storage before it's ever visible under the real name) →
/// `fs::rename` (atomic same-filesystem move) → best-effort fsync of the
/// parent directory (makes the rename's directory-entry update durable
/// too — without this, a crash immediately after rename can, on some
/// filesystems, leave the directory entry still pointing at the old inode
/// after an unclean shutdown, even though the rename "completed").
///
/// Callers are responsible for creating `path`'s parent directory first —
/// this function does not create directories, since its two current
/// callers (`vuho-settings`, and the model downloader's sidecar manifest)
/// already have their own directory-creation step with their own error
/// handling.
///
/// Std-only, per ADR-019's "deliberately std-only" scope for this crate:
/// no `tempfile` crate, just `std::fs`/`std::io`.
///
/// # Errors
///
/// Returns the underlying [`std::io::Error`] if the temp file can't be
/// created, written, or `sync_all`'d, or if the rename fails. A failed
/// parent-directory fsync is logged nowhere by this function (it has no
/// logging dependency) and does not fail the call — see the durability
/// chain above.
pub fn atomic_write(path: &Path, bytes: &[u8]) -> std::io::Result<()> {
    let tmp_path = unique_temp_path(path);
    {
        let mut file = std::fs::File::create(&tmp_path)?;
        file.write_all(bytes)?;
        file.sync_all()?;
    }
    std::fs::rename(&tmp_path, path)?;

    if let Some(parent) = path.parent() {
        // Best-effort: directory fsync isn't universally meaningful (some
        // filesystems/sandboxes don't support it), and losing the last few
        // milliseconds of directory-entry durability on an otherwise-
        // successful write is not worth turning this into a hard failure.
        let _ = std::fs::File::open(parent).and_then(|dir| dir.sync_all());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The embedded manifest must parse and carry the fields every caller
    /// (`vuho-stt-engine` and the provisioning/packaging scripts) reads.
    #[test]
    fn embedded_manifest_parses_and_has_expected_shape() {
        let m = manifest();
        assert!(!m.bundle_id.is_empty());
        assert!(!m.stt.models.is_empty());
        assert!(!m.silero.components.is_empty());
        for (id, model) in &m.stt.models {
            assert!(!model.display_name.is_empty(), "{id} has no display_name");
            assert!(!model.repo.is_empty(), "{id} has no repo");
            assert!(!model.dir_name.is_empty(), "{id} has no dir_name");
            assert!(!model.min_macos.is_empty(), "{id} has no min_macos");
            assert!(!model.components().is_empty(), "{id} has no assets");
        }
    }

    /// A `default_model` naming nothing would make
    /// `SttManifest::default_model_entry` panic on every caller.
    #[test]
    fn default_model_names_a_registered_model() {
        let m = manifest();
        assert!(
            m.stt.model(&m.stt.default_model).is_some(),
            "default_model {} is not among {:?}",
            m.stt.default_model,
            m.stt.models.keys().collect::<Vec<_>>()
        );
    }

    /// The embedded lock must parse and carry the fields
    /// `vuho-model-fetch`'s `availability()`/`download()` need, for every
    /// model the manifest declares.
    #[test]
    fn embedded_lock_parses_and_matches_manifest() {
        let l = lock();
        let m = manifest();
        assert_eq!(l.schema_version, 2);
        for (id, locked) in &l.models {
            let model = m
                .stt
                .model(id)
                .unwrap_or_else(|| panic!("lock names {id}, which the manifest does not"));
            assert_eq!(locked.dir_name, model.dir_name, "{id} dir_name");
            assert_eq!(locked.revision, model.revision, "{id} revision");
            assert!(!locked.files.is_empty(), "{id} locks no files");
            assert_eq!(
                locked.total_bytes,
                locked.files.iter().map(|f| f.size).sum::<u64>(),
                "{id} total_bytes"
            );
            for f in &locked.files {
                assert_eq!(f.sha256.len(), 64, "sha256 must be 64 hex chars: {f:?}");
            }
        }
    }

    /// Every manifest model must be locked and vice versa — a model in one
    /// file only is a half-landed provisioning change that would fail at
    /// download time instead of here.
    #[test]
    fn manifest_and_lock_describe_the_same_model_ids() {
        let manifest_ids: Vec<&String> = manifest().stt.models.keys().collect();
        let lock_ids: Vec<&String> = lock().models.keys().collect();
        assert_eq!(manifest_ids, lock_ids);
    }

    // ── `resolve_model_folder` candidate-ordering tests ─────────────────

    /// The candidate list a `NotFound` carries, asserting the variant on
    /// the way — an `InvalidDirName` here would mean the resolver never got
    /// as far as trying anything.
    fn tried(err: &ModelPathError) -> &[PathBuf] {
        match err {
            ModelPathError::NotFound { tried } => tried,
            ModelPathError::InvalidDirName(invalid) => {
                panic!("expected a NotFound, got {invalid}")
            }
        }
    }

    /// A unique temp directory, removed on drop, for building fake
    /// candidate model directories in tests without touching the real
    /// workspace `models/` or `$HOME`.
    struct TempDir(PathBuf);

    impl TempDir {
        fn new(label: &str) -> Self {
            static SEQ: AtomicU64 = AtomicU64::new(0);
            let seq = SEQ.fetch_add(1, Ordering::Relaxed);
            let dir = std::env::temp_dir().join(format!(
                "vuho-model-paths-test-{label}-{}-{seq}",
                std::process::id()
            ));
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).expect("create temp dir");
            Self(dir)
        }
    }

    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    /// RAII guard around a real subdirectory of `dev_models_dir()` — used
    /// only by the handful of tests below that must exercise the *actual*
    /// dev-dir candidate `resolve_model_folder` walks (a fixed,
    /// compile-time path derived from `CARGO_MANIFEST_DIR`, so it cannot be
    /// swapped for a fake temp dir the way the other candidates can).
    ///
    /// `dev_models_dir()` resolves to the real workspace `models/` — the
    /// same tree `./scripts/fetch-model.sh` provisions ~496 MB of real
    /// model weights into on a developer's machine. `name` must already be
    /// a test-unique string (every caller below passes one derived from its
    /// own test name), and this guard's `Drop` removes exactly that
    /// directory — unlike a bare `create_dir_all`/`remove_dir_all` pair, a
    /// panic mid-test still runs the destructor and leaves nothing behind
    /// in a directory a previous incident (a symlink committed into this
    /// same tree, destroying the real 496 MB checkout on merge) has already
    /// shown is unsafe to touch carelessly.
    struct RealDevDirGuard(PathBuf);

    impl RealDevDirGuard {
        fn create(name: &str) -> Self {
            let dir = dev_models_dir().join(name);
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).expect("create real dev-dir candidate");
            Self(dir)
        }
    }

    impl Drop for RealDevDirGuard {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    /// RAII guard that sets an env var for the test and restores its prior
    /// value on drop — keeps env-mutating tests from leaking state into
    /// whichever test runs next in the same process.
    struct EnvGuard {
        key: &'static str,
        prev: Option<String>,
    }

    impl EnvGuard {
        fn set(key: &'static str, value: &str) -> Self {
            let prev = std::env::var(key).ok();
            // SAFETY: tests in this module run single-threaded with
            // respect to each other's use of these specific keys (each
            // uses a `VUHO_MODEL_PATHS_TEST_*`-prefixed or `HOME` key
            // guarded by this same RAII type, restored before the next
            // test can observe it).
            unsafe { std::env::set_var(key, value) };
            Self { key, prev }
        }
    }

    impl Drop for EnvGuard {
        fn drop(&mut self) {
            match &self.prev {
                Some(v) => unsafe { std::env::set_var(self.key, v) },
                None => unsafe { std::env::remove_var(self.key) },
            }
        }
    }

    #[test]
    fn resolve_model_folder_honors_full_folder_env_override() {
        let spec = ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_FOLDER_OVERRIDE",
            env_name: "VUHO_MODEL_PATHS_TEST_NAME_OVERRIDE",
            default_dir_name: "default-name",
        };
        let _guard = EnvGuard::set(
            "VUHO_MODEL_PATHS_TEST_FOLDER_OVERRIDE",
            "/definitely/not/a/model",
        );
        let err = resolve_model_folder(&spec).expect_err("nonexistent folder must not resolve");

        // The env override is always candidate 1 — assert only its
        // position, not the full `tried` list: later candidates (dev dir,
        // user dir) depend on process-wide state (`$HOME`) this test does
        // not control, unlike the dedicated ordering tests below.
        assert_eq!(
            tried(&err).first(),
            Some(&PathBuf::from("/definitely/not/a/model"))
        );
    }

    /// Serializes every test below that mutates the process-wide `HOME`
    /// env var, so two such tests running concurrently (the default for
    /// `cargo test`) never observe each other's fake `$HOME` mid-check.
    static HOME_ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// Falsification target: `env_folder` must win over a real, existing
    /// dev-dir candidate — not just be tried first when nothing else
    /// exists.
    #[test]
    fn env_override_beats_an_existing_dev_dir_candidate() {
        // `dev_models_dir()` is a fixed, compile-time path
        // (`CARGO_MANIFEST_DIR`-derived), so exercise the real one: create
        // the real workspace `models/<name>` directory for the duration of
        // this test.
        let name = "vuho-model-paths-test-env-beats-dev";
        let _dev_dir_guard = RealDevDirGuard::create(name);

        let env_target = TempDir::new("env-override-target");
        let spec = ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_ENV_BEATS_DEV",
            env_name: "VUHO_MODEL_PATHS_TEST_ENV_BEATS_DEV_NAME",
            default_dir_name: name,
        };
        let _guard = EnvGuard::set(
            "VUHO_MODEL_PATHS_TEST_ENV_BEATS_DEV",
            &env_target.0.display().to_string(),
        );

        let resolved = resolve_model(&spec).expect("env override resolves");
        assert_eq!(resolved.path, env_target.0);
        assert_eq!(resolved.source, ModelSource::EnvOverride);
    }

    /// Falsification target: a full-path override that does not exist must
    /// be an error naming that path — never a silent fall-through to a
    /// candidate the operator did not ask for.
    ///
    /// A typo in `VUHO_MODEL_FOLDER` that quietly resolves to the workspace
    /// `models/` checkout would report success while loading a different
    /// model, leaving no way to notice the override was ignored. This test
    /// fails if the override is ever demoted to merely the first entry of
    /// the candidate list.
    #[test]
    fn missing_env_override_errors_instead_of_falling_through_to_dev_dir() {
        let name = "vuho-model-paths-test-env-terminal";
        let _dev_dir_guard = RealDevDirGuard::create(name);

        let spec = ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_ENV_TERMINAL",
            env_name: "VUHO_MODEL_PATHS_TEST_ENV_TERMINAL_NAME",
            default_dir_name: name,
        };
        let bogus = "/vuho-model-paths-test/definitely-not-a-real-directory";
        let _guard = EnvGuard::set("VUHO_MODEL_PATHS_TEST_ENV_TERMINAL", bogus);

        let err = resolve_model_folder(&spec)
            .expect_err("a nonexistent override must not resolve to the dev dir");
        assert_eq!(
            tried(&err),
            &[PathBuf::from(bogus)],
            "the override must be the only candidate tried"
        );
    }

    /// Falsification target: the workspace dev-dir candidate (3) must beat
    /// the user-data candidate (4) even when both exist — this is what
    /// keeps `cargo run` / `cargo test` / `test-stt-ffi` resolving the
    /// developer's real checkout instead of a stale download.
    #[test]
    fn dev_dir_beats_user_dir_when_both_exist() {
        let _lock = HOME_ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        let name = "vuho-model-paths-test-dev-beats-user";
        let dev_dir_guard = RealDevDirGuard::create(name);
        let dev_dir = dev_dir_guard.0.clone();

        let fake_home = TempDir::new("dev-beats-user-home");
        let user_dir = fake_home
            .0
            .join("Library")
            .join("Application Support")
            .join("Vuho")
            .join("models")
            .join(name);
        std::fs::create_dir_all(&user_dir).expect("create user-dir candidate");

        let _guard = EnvGuard::set("HOME", &fake_home.0.display().to_string());
        let spec = ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_UNSET_DEV_BEATS_USER",
            env_name: "VUHO_MODEL_PATHS_TEST_UNSET_DEV_BEATS_USER_NAME",
            default_dir_name: name,
        };

        let resolved = resolve_model(&spec).expect("dev dir resolves");
        assert_eq!(resolved.path, dev_dir);
        assert_eq!(resolved.source, ModelSource::DevTree);
    }

    /// The user-data candidate (4) resolves when it's the only one that
    /// exists — the whole point of ADR-020's addition.
    #[test]
    fn user_dir_resolves_when_it_is_the_only_existing_candidate() {
        let _lock = HOME_ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        let name = "vuho-model-paths-test-user-dir-only";
        let fake_home = TempDir::new("user-dir-only-home");
        let user_dir = fake_home
            .0
            .join("Library")
            .join("Application Support")
            .join("Vuho")
            .join("models")
            .join(name);
        std::fs::create_dir_all(&user_dir).expect("create user-dir candidate");

        let _guard = EnvGuard::set("HOME", &fake_home.0.display().to_string());
        let spec = ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_UNSET_USER_DIR_ONLY",
            env_name: "VUHO_MODEL_PATHS_TEST_UNSET_USER_DIR_ONLY_NAME",
            default_dir_name: name,
        };

        let resolved = resolve_model(&spec).expect("user dir resolves");
        assert_eq!(resolved.path, user_dir);
        assert_eq!(resolved.source, ModelSource::UserData);
    }

    #[test]
    fn resolve_model_folder_falls_back_to_workspace_dev_dir() {
        let spec = ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_UNSET_FOLDER",
            env_name: "VUHO_MODEL_PATHS_TEST_UNSET_NAME",
            default_dir_name: "definitely-not-a-provisioned-model",
        };
        let err = resolve_model_folder(&spec).expect_err("unprovisioned dev dir must not resolve");
        assert!(
            tried(&err)
                .iter()
                .any(|p| p.ends_with("models/definitely-not-a-provisioned-model")),
            "expected a workspace-relative models/ path among tried candidates, got {:?}",
            tried(&err)
        );
    }

    /// When nothing resolves, `tried` must list every candidate that was
    /// actually available to try — the dev dir and (with `HOME` set) the
    /// user-data dir. `bundle_resources_dir()` is `None` under `cargo test`
    /// (no `.app` ancestor), so it's correctly absent here rather than a
    /// third entry. The full-path override is deliberately left unset: it
    /// is terminal, and covered separately by
    /// `missing_env_override_errors_instead_of_falling_through_to_dev_dir`.
    #[test]
    fn tried_lists_every_available_candidate_on_failure() {
        let _lock = HOME_ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        let name = "vuho-model-paths-test-tried-lists-all";
        let fake_home = TempDir::new("tried-lists-all-home");
        let _guard_home = EnvGuard::set("HOME", &fake_home.0.display().to_string());
        // No `env_folder` override is set: the full-path override is
        // terminal (see `candidate_paths`), so setting it would collapse
        // the list to that one entry and this test would stop covering the
        // multi-candidate walk it exists to pin.
        let spec = ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_TRIED_FOLDER_UNSET",
            env_name: "VUHO_MODEL_PATHS_TEST_TRIED_NAME",
            default_dir_name: name,
        };

        let err = resolve_model_folder(&spec).expect_err("nothing here should resolve");
        assert_eq!(
            tried(&err),
            &[
                dev_models_dir().join(name),
                fake_home
                    .0
                    .join("Library")
                    .join("Application Support")
                    .join("Vuho")
                    .join("models")
                    .join(name),
            ]
        );
    }

    // ── `dir_name_for` validation tests ──────────────────────────────────

    fn name_spec(env_name: &'static str, default_dir_name: &'static str) -> ModelSpec<'static> {
        ModelSpec {
            env_folder: "VUHO_MODEL_PATHS_TEST_NAME_VALIDATION_FOLDER_UNSET",
            env_name,
            default_dir_name,
        }
    }

    #[test]
    fn a_plain_directory_name_is_accepted() {
        let spec = name_spec(
            "VUHO_MODEL_PATHS_TEST_NAME_PLAIN_UNSET",
            "parakeet-tdt-0.6b-v3-coreml",
        );
        assert_eq!(
            dir_name_for(&spec).expect("a plain name resolves"),
            "parakeet-tdt-0.6b-v3-coreml"
        );
    }

    /// Falsification target: the traversal that defeats `delete`'s
    /// `starts_with` guard. `<user_dir>/../../../../tmp/victim` passes a
    /// component-wise prefix test, so the name has to be refused here,
    /// before either the downloader or the deleter ever joins it.
    #[test]
    fn a_name_that_escapes_the_user_directory_is_refused() {
        for escape in [
            "../../../../tmp/victim",
            "..",
            "/tmp/victim",
            "sub/dir",
            "models/",
            ".",
            "./models",
        ] {
            let spec = name_spec("VUHO_MODEL_PATHS_TEST_NAME_ESCAPE", "default-name");
            let _guard = EnvGuard::set("VUHO_MODEL_PATHS_TEST_NAME_ESCAPE", escape);

            let err = dir_name_for(&spec)
                .expect_err("a name that is not one plain component must be refused");
            assert_eq!(err.value, escape);
            assert_eq!(err.origin, "VUHO_MODEL_PATHS_TEST_NAME_ESCAPE");
        }
    }

    /// A refused name must never quietly fall back to the manifest default:
    /// the operator would then download into, and later delete, a directory
    /// they did not name.
    #[test]
    fn a_refused_override_does_not_fall_back_to_the_default() {
        let spec = name_spec("VUHO_MODEL_PATHS_TEST_NAME_NO_FALLBACK", "default-name");
        let _guard = EnvGuard::set("VUHO_MODEL_PATHS_TEST_NAME_NO_FALLBACK", "../escape");

        let err = resolve_model(&spec).expect_err("resolution must not proceed");
        assert!(
            matches!(err, ModelPathError::InvalidDirName(ref invalid) if invalid.value == "../escape"),
            "{err}"
        );
    }

    /// Every `dir_name` the embedded manifest ships must already satisfy the
    /// rule, or the default path would be refused before an operator ever
    /// set an env var.
    #[test]
    fn every_manifest_dir_name_is_a_plain_directory_name() {
        for (id, model) in &manifest().stt.models {
            assert!(
                plain_dir_name(model.dir_name.clone(), MANIFEST_ORIGIN).is_ok(),
                "{id} has an unusable dir_name {:?}",
                model.dir_name
            );
        }
    }

    // ── `resources_dir_for_exe` path-shape tests (finding 9) ────────────────

    #[test]
    fn resources_dir_for_exe_resolves_the_innermost_enclosing_bundle() {
        let tmp = std::env::temp_dir().join("vuho-test-nested-bundle");
        let _ = std::fs::remove_dir_all(&tmp);
        let inner_contents = tmp.join("Foo.app/Contents/PlugIns/Bar.app/Contents");
        std::fs::create_dir_all(&inner_contents).expect("create nested bundle dirs");
        // The OUTER .app's Contents also exists, as a decoy: a correct
        // implementation must resolve to the INNER (Bar.app) bundle, the
        // one that actually encloses `exe`, not the outer one.
        std::fs::create_dir_all(tmp.join("Foo.app/Contents")).expect("create outer Contents");

        let exe = inner_contents.join("MacOS/Bar");
        let resolved =
            resources_dir_for_exe(&exe).expect("must resolve the innermost enclosing bundle");
        assert_eq!(
            resolved,
            tmp.join("Foo.app/Contents/PlugIns/Bar.app/Contents/Resources")
        );

        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn resources_dir_for_exe_ignores_a_contents_backup_lookalike() {
        let tmp = std::env::temp_dir().join("vuho-test-contents-backup");
        let _ = std::fs::remove_dir_all(&tmp);
        // "Contents-backup" shares ".app/Contents" as a literal string
        // prefix with a real bundle's "Contents" directory, but is not one.
        std::fs::create_dir_all(tmp.join("Foo.app/Contents-backup"))
            .expect("create Contents-backup lookalike");

        let exe = tmp.join("Foo.app/Contents-backup/MacOS/Foo");
        assert!(
            resources_dir_for_exe(&exe).is_none(),
            "a `Contents-backup` sibling must not be mistaken for a real `Contents` directory"
        );

        std::fs::remove_dir_all(&tmp).ok();
    }

    // ── `atomic_write` tests ─────────────────────────────────────────────

    #[test]
    fn atomic_write_creates_the_file_with_exact_contents_and_no_stray_temp() {
        let dir = TempDir::new("atomic-write-basic");
        let path = dir.0.join("out.bin");

        atomic_write(&path, b"hello world").expect("atomic_write succeeds");

        assert_eq!(std::fs::read(&path).unwrap(), b"hello world");
        let leftovers: Vec<_> = std::fs::read_dir(&dir.0)
            .unwrap()
            .map(|e| e.unwrap().file_name())
            .collect();
        assert_eq!(
            leftovers,
            vec![std::ffi::OsString::from("out.bin")],
            "no temp file should survive a successful atomic_write"
        );
    }

    #[test]
    fn atomic_write_replaces_existing_content_atomically() {
        let dir = TempDir::new("atomic-write-replace");
        let path = dir.0.join("out.bin");
        std::fs::write(&path, b"old").unwrap();

        atomic_write(&path, b"new content").expect("atomic_write succeeds");

        assert_eq!(std::fs::read(&path).unwrap(), b"new content");
    }

    #[test]
    fn unique_temp_path_differs_across_calls() {
        let base = PathBuf::from("/tmp/whatever/out.bin");
        let a = unique_temp_path(&base);
        let b = unique_temp_path(&base);
        assert_ne!(a, b);
        assert_eq!(a.parent(), base.parent());
        assert_eq!(b.parent(), base.parent());
    }
}
